#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri
bundle exec rubocop -D --config docs/.rubocop.yml
bundle exec docs/script/validate-html
gem build docs/jekyll-theme-tactile.gemspec
